<template>
	<div
		class="game-page min-h-screen flex flex-col justify-center items-center bg-gradient-to-b from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 text-center px-4"
	>
		<div class="max-w-4xl w-full">
			<div v-if="isGamePlaying" class="mb-12">
				<div class="flex justify-between items-center mb-3">
					<span class="text-gray-900 font-medium text-lg">
						Question {{ questionIndex + 1 }} of
						{{ questionsLen }}
					</span>
					<span class="text-gray-900 font-medium text-lg">
						Score: {{ score }}/{{ questionIndex }}
					</span>
				</div>
				<div class="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2.5">
					<div
						class="bg-blue-600 h-2.5 rounded-full transition-all duration-500"
						:style="{
							width: `${(questionIndex / questionsLen) * 100}%`,
						}"
					></div>
				</div>
			</div>

			<div v-if="!isGamePlaying" class="keynote-panel">
				<h1 class="text-gray-900 text-5xl font-bold mb-6">AI Detection Challenge</h1>
				<h2 class="text-gray-900 text-3xl font-bold mb-8">Ready to Begin?</h2>
				<p class="text-gray-800 text-xl mb-12 max-w-2xl mx-auto">
					You'll be presented with a series of content pieces. Your challenge is to determine which
					are created by humans and which are generated by AI.
				</p>
				<button @click="gameStore.startGame" class="action-button">
					<span class="flex items-center">
						<span>Start Challenge</span>
						<svg
							class="w-4 h-4 ml-2"
							aria-hidden="true"
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 14 10"
						>
							<path
								stroke="currentColor"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M1 5h12m0 0L9 1m4 4L9 9"
							/>
						</svg>
					</span>
				</button>
			</div>
			<game-question v-else-if="isGamePlaying" :question="currentQuestion" />

			<game-results
				v-else
				:results="currentGame.userAnswers"
				:questions="currentGame.questions"
				:message="gameStore.getResultMessage()"
				@restart="gameStore.resetGame()"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import GameQuestion from '../components/game/GameQuestion.vue';
import GameResults from '../components/game/GameResults.vue';
import { useGame } from '../composables/game';

const router = useRouter();
const gameStore = useGame();

const currentGame = computed(() => gameStore.game.value);

const isGamePlaying = computed<boolean>(
	() => currentGame.value.questions.length !== currentGame.value.userAnswers.length,
);

const questionIndex = computed(() => gameStore.game.value.currentQuestionIndex);

const questionsLen = computed(() => gameStore.game.value.questions.length);

const score = computed(() => gameStore.score.value);

const currentQuestion = computed(() => gameStore.getNextQuestion());
</script>

<style scoped>
.game-page {
	transition: background-color 0.3s ease;
}

.keynote-panel {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 3rem 2rem;
	border-radius: 1rem;
	background-color: transparent;
}

.keynote-button {
	display: none; /* Hide old button style */
}

.action-button {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	padding: 0.75rem 1.75rem;
	font-size: 1rem;
	font-weight: 600;
	color: white;
	background: linear-gradient(135deg, #0071e3, #42a0ff);
	border-radius: 1.5rem;
	cursor: pointer;
	transition: all 0.2s ease;
	border: none;
	box-shadow: 0 2px 10px rgba(0, 113, 227, 0.4);
}

.action-button:hover {
	transform: translateY(-2px);
	box-shadow: 0 4px 15px rgba(0, 113, 227, 0.5);
	background: linear-gradient(135deg, #0077ed, #47a5ff);
}

.action-button:active {
	transform: translateY(0);
	box-shadow: 0 2px 8px rgba(0, 113, 227, 0.4);
}
</style>
