<template>
  <div class="home-page">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
      <!-- Hero Section -->
      <section class="flex flex-col justify-between items-center mb-16">
        <div class="text-center">
          <h2 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-3xl md:text-4xl font-bold mb-4">
            Can You Spot AI-Generated Content?
          </h2>
          <p :class="isDark ? 'text-gray-300' : 'text-gray-600'" class="text-lg md:text-xl mb-8 max-w-3xl mx-auto">
            Test your ability to distinguish between human-created and AI-generated images and text. The
            line is blurring - can you tell the difference?
          </p>
          <router-link 
            to="/game"
            class="inline-block bg-blue-600 text-white px-6 py-3 md:px-8 md:py-4 rounded-lg text-base md:text-lg font-semibold hover:bg-blue-700 transform transition hover:scale-105 shadow-lg"
          >
            Start The Challenge
          </router-link>
        </div>
        
        <div class="mt-12 w-full max-w-4xl">
          <div :class="isDark ? 'bg-gray-800' : 'bg-white'" class="rounded-xl shadow-lg overflow-hidden">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-0">
              <div class="relative">
                <img 
                  src="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1064&q=80" 
                  alt="Human Created Photography" 
                  class="w-full h-64 object-cover" 
                />
                <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4">
                  <p class="text-white font-medium">Human Created</p>
                </div>
              </div>
              <div class="relative">
                <img 
                  src="https://images.unsplash.com/photo-1659371254553-6fb8e3209b1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" 
                  alt="AI Generated Art" 
                  class="w-full h-64 object-cover" 
                />
                <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4">
                  <p class="text-white font-medium">AI Generated</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- How It Works Section -->
      <section class="mb-16">
        <h3 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-2xl font-bold mb-8 text-center">
          How It Works
        </h3>
        
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <!-- Step 1 -->
          <div 
            :class="isDark ? 'bg-gray-800 shadow-gray-700/30' : 'bg-white shadow-lg'" 
            class="rounded-xl p-6 flex flex-col justify-between h-full"
          >
            <div>
              <div class="h-12 w-12 bg-blue-100 rounded-full flex items-center justify-center mb-4">
                <span class="text-blue-600 font-bold text-xl">1</span>
              </div>
              <h4 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-lg font-semibold mb-2">
                Analyze Content
              </h4>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'">
                You'll be shown a series of images and text snippets. Take your time to examine each one carefully.
              </p>
            </div>
          </div>

          <!-- Step 2 -->
          <div 
            :class="isDark ? 'bg-gray-800 shadow-gray-700/30' : 'bg-white shadow-lg'" 
            class="rounded-xl p-6 flex flex-col justify-between h-full"
          >
            <div>
              <div class="h-12 w-12 bg-green-100 rounded-full flex items-center justify-center mb-4">
                <span class="text-green-600 font-bold text-xl">2</span>
              </div>
              <h4 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-lg font-semibold mb-2">
                Make Your Decision
              </h4>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'">
                For each item, decide whether you think it was created by a human or generated by AI.
              </p>
            </div>
          </div>

          <!-- Step 3 -->
          <div 
            :class="isDark ? 'bg-gray-800 shadow-gray-700/30' : 'bg-white shadow-lg'" 
            class="rounded-xl p-6 flex flex-col justify-between h-full"
          >
            <div>
              <div class="h-12 w-12 bg-purple-100 rounded-full flex items-center justify-center mb-4">
                <span class="text-purple-600 font-bold text-xl">3</span>
              </div>
              <h4 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-lg font-semibold mb-2">
                See Your Results
              </h4>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'">
                After completing the challenge, get your score and learn about the telltale signs you missed or caught.
              </p>
            </div>
          </div>
        </div>
      </section>

      <!-- Why It Matters Section -->
      <section class="mb-8">
        <h3 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-2xl font-bold mb-8 text-center">
          Why It Matters
        </h3>
        
        <div :class="isDark ? 'bg-gray-800 shadow-gray-700/30' : 'bg-white shadow-lg'" class="rounded-xl p-8">
          <div class="flex flex-col md:flex-row gap-8 items-center">
            <div class="md:w-1/2">
              <h4 :class="isDark ? 'text-white' : 'text-gray-900'" class="text-xl font-semibold mb-4">
                Developing Critical Media Literacy
              </h4>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'" class="mb-4">
                As AI-generated content becomes increasingly sophisticated, the ability to distinguish
                between human and machine-created work is becoming an essential skill.
              </p>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'" class="mb-4">
                This game helps you develop a critical eye for the subtle tells that can reveal AI
                authorship, while also highlighting how the gap between human and AI creation is rapidly
                narrowing.
              </p>
              <p :class="isDark ? 'text-gray-300' : 'text-gray-600'">
                After each round, you'll receive detailed insights about what you missed and what you
                correctly identified, helping you become more discerning in the future.
              </p>
            </div>
            <div class="md:w-1/2">
              <div class="rounded-lg overflow-hidden shadow-lg">
                <img 
                  src="https://img.freepik.com/free-vector/robots-concept-illustration_114360-1825.jpg" 
                  alt="Cartoon Robots" 
                  class="w-full h-64 object-cover" 
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
// Props
interface Props {
  isDark?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isDark: false
});
</script> 