# https://taskfile.dev

version: "3"

vars:
  APP_NAME: centrs
  APP_ENV: development
  APP_VERSION: 0.0.1

dotenv:
  - ".env"

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: install

  install:
    desc: "Install dependencies"
    cmds:
      - go mod download
      - go install github.com/go-task/task/v3/cmd/task@latest

  lint:
    desc: "Run linter"
    cmd: golangci-lint run ./...

  build:
    desc: "Build binary"
    cmd: go build -o ./bin/centrs ./cmd/centrs/main.go
    requires:
      vars:
        - APP_NAME

  start:
    desc: "Start binary"
    cmd: ./bin/{{.APP_NAME}}
    requires:
      vars:
        - APP_NAME
